USE test;

CREATE TABLE IF NOT EXISTS employee (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
email VARCHAR(50),
county VARCHAR(100) NOT NULL,
status VARCHAR(100) NOT NULL,
address TEXT NOT NULL,
married VARCHAR(10) NOT NULL,
employed VARCHAR(10) NOT NULL,
mobile VARCHAR(100) NOT NULL);
